CondominioWeb/Models/Cobranza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CondominioWeb.Models
{
    public class Cobranza
    {
        public string Propiedad { get; set; }
    }
}

CondominioWeb/Controllers/CobranzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CondominioWeb.Models;
using CondominioWeb.DAL;
using System.Data;

namespace CondominioWeb.Controllers
{
    public class CobranzaController : Controller
    {
        // GET: Cobranza
        public ActionResult Index()
        {
            var pro = CargarGrilla();

            IEnumerable<SelectListItem> Prop = pro.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Numero
            });

            ViewBag.Prop = Prop;

            return View();
        }

        [HttpPost]
        public ActionResult Detalle(Cobranza cob)
        {
            return View(cob);
        }

        private List<ListPropiedad> CargarGrilla()
        {
            var propList = new List<ListPropiedad>();
            using (var dt = BaseDatos.ExecuteDataTable("sp_c_list_propiedad"))
            {
                foreach (DataRow row in dt.Rows)
                {
                    var prop = new ListPropiedad()
                    {
                        Id = (int)row["id"],
                        Numero = row["numero"].ToString(),
                    };
                    propList.Add(prop);
                }
            }
            return propList;
        }
    }
}

CondominioWeb/Views/Cobranza/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="col-lg-6">
        <div class="card position-relative">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Generaci&oacute;n Cartas de Cobranza</h6>
            </div>
            @using (Html.BeginForm("Detalle", "Cobranza", FormMethod.Post))
            {
            <div class="card-body">

                <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                    <a class="navbar-brand" href="#">Propiedad:</a>
                    <ul class="navbar-nav ml-auto">
                        <div class="form-group">
                            @Html.DropDownList("Propiedad",
     new SelectList(ViewBag.Prop, "Value", "Text"),
    "Seleccionar...",
    new { @class = "form-control" })
                        </div>
                    </ul>
                </nav>

                <p>&nbsp;</p>

                <p>
                <p>
                    <a href="/Exportar/Index/2" class="btn btn-success">Generar PDF</a>
                    &nbsp;
                    <a href="#" class="btn btn-secondary">Enviar por email</a>
                    &nbsp;
                    <a href="/Home/" class="btn btn-warning">Volver</a>
                </p>
                </p>
            </div>
            }
            </div>
    </div>
</body>
</html>