CondominioWeb/Models/Propiedad.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CondominioWeb.Models
{
    public class Propiedad
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public Tipo _Tipo { get; set; }
        public string Prorrateo { get; set; }
        public string Propietario { get; set; }
        public EstadoPro _Estado_Prop { get; set; }
        public Boolean Estado { get; set; }
    }

    public class ListPropiedad {
        public int Id { get; set; }
        public string Numero { get; set; }
    }

    public enum Tipo { Casa, Departamento, Estacionamiento, Bodega };

    public enum EstadoPro { Habitada, Abandonada, Arrendada, Propietario };
}

CondominioWeb/Controllers/PropiedadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CondominioWeb.Models;
using CondominioWeb.DAL;
using System.Data;

namespace CondominioWeb.Controllers
{
    public class PropiedadController : Controller
    {
        // GET: Propiedad
        public ActionResult Index()
        {
            var cop = CargarGrilla(0, 0);

            ViewBag.EmployeeList = cop;

            return View();
        }

        public ActionResult Crear()
        {
            return View();
        }

        private List<Propiedad> CargarGrilla(int tipo, int id)
        {
            var propiedadList = new List<Propiedad>();
            using (var dt = BaseDatos.ExecuteDataTable("sp_c_propiedad", tipo, id))
            {
                foreach (DataRow row in dt.Rows)
                {
                    var propiedad = new Propiedad()
                    {
                        Id = (int)row["id"],
                        Numero = row["numero"].ToString(),
                        _Tipo = (Tipo)Enum.Parse(typeof(Tipo), row["tipo"].ToString(), true),
                        Prorrateo = row["prorrateo"].ToString(),
                        Propietario = row["propietario"].ToString(),
                        _Estado_Prop = (EstadoPro)Enum.Parse(typeof(EstadoPro), row["estado_prop"].ToString(), true),
                    };
                    propiedadList.Add(propiedad);
                }
            }
            return propiedadList;
        }

        [HttpPost]
        public ActionResult Crear(Propiedad pro)
        {
            var res = Guardar(pro);

            if (res.Contains("Error"))
            {
                ViewBag.Tipo = 1;
            }
            else
            {
                ViewBag.Tipo = 0;
            }

            ViewBag.Message = res;

            return View();
        }

        private String Guardar(Propiedad pro)
        {
            try
            {
                BaseDatos.ExecuteSql("sp_i_registro_propiedad", pro.Numero, pro._Tipo, pro.Prorrateo, pro.Propietario, pro._Estado_Prop);
                return "Registro guardado";
            }
            catch (Exception ex)
            {
                return "Error: " + ex.Message;
            }
        }

        public JsonResult DeleteRealState(int EmployeeId)
        {
            bool res = EliminarProp(EmployeeId);

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        private bool EliminarProp(int PropID)
        {
            try
            {
                BaseDatos.ExecuteSql("sp_d_registro_propiedad", PropID);
                return true;
            }
            catch
            {
                return false;
            }
        }

        public ActionResult Editar(int id)
        {
            var cop = CargarGrilla(1, id);

            var copro = cop.Where(c => c.Id == id).FirstOrDefault();

            return View(copro);
        }

        [HttpPost]
        public ActionResult Editar(Propiedad pro)
        {
            var res = Actualizar(pro);

            if (res.Contains("Error"))
            {
                ViewBag.Tipo = 1;
            }
            else
            {
                ViewBag.Tipo = 0;
            }

            ViewBag.Message = res;

            return View();
        }

        private String Actualizar(Propiedad pro)
        {
            try
            {
                BaseDatos.ExecuteSql("sp_u_registro_propiedad", pro.Id, pro.Numero, pro._Tipo, pro.Prorrateo, pro.Propietario, pro._Estado_Prop);
                return "Registro actualizado";
            }
            catch (Exception ex)
            {
                return "Error: " + ex.Message;
            }
        }
    }
}

CondominioWeb/Views/Propiedad/Crear.cshtml
@using CondominioWeb.Models
@model Propiedad

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!-- <div class="col-lg-5 d-none d-lg-block bg-register-image"></div> -->
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Registro Propiedades</h1>
                        </div>

                        @if (ViewBag.Tipo == 1)
                        {
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.Message
                            </div>
                        }
                        @if (ViewBag.Tipo == 0)
                        {
                            <div class="alert alert-success" role="alert">
                                @ViewBag.Message
                            </div>
                        }

                        @using (Html.BeginForm("Crear", "Propiedad", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="Rut">N&uacute;mero</label>
                                @Html.TextBox("Numero", null, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Genero">Tipo</label>
                                @Html.DropDownList("_Tipo",
                new SelectList(Enum.GetValues(typeof(Tipo))),
                "Seleccionar...",
                new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Email">Prorrateo</label>
                                @Html.TextBox("Prorrateo", null, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Email">Propietario</label>
                                @Html.TextBox("Propietario", null, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Genero">Estado</label>
                                @Html.DropDownList("_Estado_Prop",
                new SelectList(Enum.GetValues(typeof(EstadoPro))),
                "Seleccionar...",
                new { @class = "form-control" })
                            </div>

                            <p>
                                <button type="submit" class="btn btn-success">Registrar</button>
                                &nbsp;
                                <a href="/propiedad/" class="btn btn-warning">Volver</a>
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CondominioWeb/Views/Propiedad/Editar.cshtml
@using CondominioWeb.Models
@model Propiedad

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!-- <div class="col-lg-5 d-none d-lg-block bg-register-image"></div> -->
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Registro Propiedades</h1>
                        </div>

                        @if (ViewBag.Tipo == 1)
                        {
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.Message
                            </div>
                        }
                        @if (ViewBag.Tipo == 0)
                        {
                            <div class="alert alert-success" role="alert">
                                @ViewBag.Message
                            </div>
                        }

                        @using (Html.BeginForm("Editar", "Propiedad", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="Rut">N&uacute;mero</label>
                                @Html.TextBox("Numero", null, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Genero">Tipo</label>
                                @Html.DropDownList("_Tipo",
                new SelectList(Enum.GetValues(typeof(Tipo))),
                "Seleccionar...",
                new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label for="Email">Prorrateo</label>
                                @Html.TextBox("Prorrateo", null, new { @class = "form-control", placeholder = "nombre@ejemplo.com" })
                            </div>

                            <div class="form-group">
                                <label for="Email">Propietario</label>
                                @Html.TextBox("Propietario", null, new { @class = "form-control", placeholder = "nombre@ejemplo.com" })
                            </div>

                            <div class="form-group">
                                <label for="Genero">Estado</label>
                                @Html.DropDownList("_Estado_Prop",
                new SelectList(Enum.GetValues(typeof(EstadoPro))),
                "Seleccionar...",
                new { @class = "form-control" })
                            </div>

                            <p>
                                <button type="submit" class="btn btn-success">Actualizar</button>
                                &nbsp;
                                <a href="/propiedad/" class="btn btn-warning">Volver</a>
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CondominioWeb/Views/Propiedad/Index.cshtml
<div class="container-fluid">
    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Listado Propiedades</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">

                @if (ViewBag.Tipo == 1)
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.Message
                    </div>
                }
                @if (ViewBag.Tipo == 0)
                {
                    <div class="alert alert-success" role="alert">
                        @ViewBag.Message
                    </div>
                }

                <p>
                    @Html.ActionLink("Crear Nuevo", "Crear", "Propiedad")
                </p>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>N&uacute;mero</th>
                            <th>Tipo</th>
                            <th>Prorrateo</th>
                            <th>Propietario</th>
                            <th>Estado</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    @*<tfoot>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                                <th>@Html.DisplayNameFor(model => model.Apellido)</th>
                                <th>@Html.DisplayNameFor(model => model.Telefono)</th>
                                <th>@Html.DisplayNameFor(model => model.Fec_Nac)</th>
                                <th>@Html.DisplayNameFor(model => model.Nacionalidad)</th>
                                <th>@Html.DisplayNameFor(model => model.Email)</th>
                                <th>&nbsp;</th>
                            </tr>
                        </tfoot>*@
                    <tbody>
                        @foreach (var item in ViewBag.EmployeeList)
                        {
                            <tr id="row_@item.Id">
                                <td>@item.Numero</td>
                                <td>@item._Tipo</td>
                                <td>@item.Prorrateo</td>
                                <td>@item.Propietario</td>
                                <td>@item._Estado_Prop</td>
                                <td>


                                    <a href="/propiedad/editar/@item.Id" class="btn btn-info btn-circle btn-sm" data-toggle="tooltip" data-placement="top" title="Actualizar">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                    <a href="#" class="btn btn-danger btn-circle btn-sm" data-toggle="tooltip" data-placement="top" title="Eliminar" onclick="ConfirmDelete(@item.Id)">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


                <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                <h4>Esta seguro que desea eliminar este registro? </h4>

                                <div style="text-align:center;display:none" id="loaderDiv">
                                    <img src="~/Content/img/Ring-Preloader.gif" width="150" />
                                </div>

                            </div>
                            <div class="modal-footer">
                                <a href="#" class="btn btn-default" data-dismiss="modal">Cancelar</a>
                                <a href="#" class="btn btn-success" onclick="DeleteRealState()">Confirmar</a>
                            </div>

                        </div>

                    </div>

                </div>


                @*hidden field for storing current employeeId*@
                <input type="hidden" id="hiddenEmployeeId" />



            </div>
        </div>
    </div>
</div>