CondominioWeb/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CondominioWeb.Models
{
    public class Estado
    {
        public int id { get; set; }
        public string mes { get; set; }
        public int anio { get; set; }
    }

}

CondominioWeb/Controllers/EstadosController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CondominioWeb.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using CondominioWeb.DAL;
using System.Data;

namespace CondominioWeb.Controllers
{
    public class EstadosController : Controller
    {
        public ActionResult Index()
        {
            IEnumerable<SelectListItem> Years = Enumerable.Range(2008, DateTime.UtcNow.Year - 2007).Select(x => new SelectListItem
            {
                Value = x.ToString(),
                Text = x.ToString()
            });

            IEnumerable<SelectListItem> Months = Enumerable.Range(1, 12).Select(x => new SelectListItem
            {
                Value = x.ToString(),
                Text = DateTimeFormatInfo.CurrentInfo.GetMonthName(x)
            });

            var pro = CargarGrilla();

            IEnumerable<SelectListItem> Prop = pro.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Numero
            });

            ViewBag.Years = Years;
            ViewBag.Months = Months;
            ViewBag.Prop = Prop;

            return View();
        }
        // GET: Estados
        public ActionResult Pdf()
        {
            var est = new List<Estado>
            {
                new Estado { id=1,mes="octubre",anio=2019},
                new Estado { id=2,mes="septiembre",anio=2018}
            };
            return View(est);
        }

        [HttpPost]
        public ActionResult Test(FormCollection collection)
        {
            return View();
        }

        private List<ListPropiedad> CargarGrilla()
        {
            var propList = new List<ListPropiedad>();
            using (var dt = BaseDatos.ExecuteDataTable("sp_c_list_propiedad"))
            {
                foreach (DataRow row in dt.Rows)
                {
                    var prop = new ListPropiedad()
                    {
                        Id = (int)row["id"],
                        Numero = row["numero"].ToString(),
                    };
                    propList.Add(prop);
                }
            }
            return propList;
        }
    }
}

CondominioWeb/Views/Estados/Index.cshtml
@model List<int>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="col-lg-6">
        <div class="card position-relative">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Generaci&oacute;n Estados de Cuenta</h6>
            </div>
            @using (Html.BeginForm("Test", "Estados", FormMethod.Post))
            {
            <div class="card-body">
                <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                    <a class="navbar-brand" href="#">Propiedad:</a>
                    <ul class="navbar-nav ml-auto">
                        <div class="form-group">
                            @Html.DropDownList("Propiedad",
     new SelectList(ViewBag.Prop, "Value", "Text"),
    "Seleccionar...",
    new { @class = "form-control" })
                        </div>
                    </ul>
                </nav>
                <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                    <a class="navbar-brand" href="#">Periodo:</a>
                    <ul class="navbar-nav ml-auto">
                        <div class="form-group">
                            @Html.DropDownList("Anio",
     new SelectList(ViewBag.Years, "Value", "Text"),
    "Seleccionar...",
    new { @class = "form-control" })
                        </div>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <div class="form-group">
                            @Html.DropDownList("Mes",
     new SelectList(ViewBag.Months, "Value", "Text"),
    "Seleccionar...",
    new { @class = "form-control" })
                        </div>
                    </ul>
                </nav>

                <p>
                    <a href="/Exportar/Index/1" class="btn btn-success">Generar PDF</a>
                    &nbsp;
                    <a href="#" class="btn btn-secondary">Enviar por email</a>
                    &nbsp;
                    <a href="/Home/" class="btn btn-warning">Volver</a>
                </p>

            </div>
            }
        </div>
    </div>
</body>
</html>